and (論理AND演算子) を使用
Pythonで論理AND条件を使う場合、& (ビット単位のAND演算子) ではなく、and (論理AND演算子) を使用

 2025-11-13 08:49:36,792 ERROR: Traceback (most recent call last):
   File "/media/main.py", line 422, in discord_config
     if args1 is None & args2 is None:
                 ~~~~~^~~~~~~
 TypeError: unsupported operand type(s) for &: 'NoneType' and 'NoneType'